
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/dheerajmurthy/Dev/tooling/flutter/bin/"
      - "/opt/homebrew/opt/postgresql@17/bin/"
      - "/Users/dheerajmurthy/.local/bin/"
      - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin/"
      - "/Users/dheerajmurthy/.pub-cache/bin/"
      - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin/"
      - "/usr/local/texlive/2024/bin/universal-darwin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/homebrew/bin/"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0/bin/"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0@global/bin/"
      - "/Users/dheerajmurthy/.rvm/rubies/ruby-3.3.0/bin/"
      - "/Users/dheerajmurthy/miniforge3/condabin/"
      - "/Users/dheerajmurthy/.nvm/versions/node/v23.9.0/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pkg/env/active/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/MacGPG2/bin/"
      - "/Library/TeX/texbin/"
      - "/Applications/Wireshark.app/Contents/MacOS/"
      - "/usr/local/share/dotnet/"
      - "/Users/dheerajmurthy/.dotnet/tools/"
      - "/usr/local/go/bin/"
      - "/Applications/quarto/bin/"
      - "/Users/dheerajmurthy/.cargo/bin/"
      - "/Applications/Ghostty.app/Contents/MacOS/"
      - "/Users/dheerajmurthy/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/opt/homebrew/opt/fzf/bin/"
      - "/Users/dheerajmurthy/.rvm/bin/"
    searched_directories:
      - "/Users/dheerajmurthy/Dev/tooling/flutter/bin/uname"
      - "/opt/homebrew/opt/postgresql@17/bin/uname"
      - "/Users/dheerajmurthy/.local/bin/uname"
      - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin/uname"
      - "/Users/dheerajmurthy/.pub-cache/bin/uname"
      - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin/uname"
      - "/usr/local/texlive/2024/bin/universal-darwin/uname"
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/opt/homebrew/bin/uname"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0/bin/uname"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0@global/bin/uname"
      - "/Users/dheerajmurthy/.rvm/rubies/ruby-3.3.0/bin/uname"
      - "/Users/dheerajmurthy/miniforge3/condabin/uname"
      - "/Users/dheerajmurthy/.nvm/versions/node/v23.9.0/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/Users/dheerajmurthy/.local/bin"
        - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin"
        - "/Users/dheerajmurthy/.pub-cache/bin"
        - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/usr/local/texlive/2024/bin/universal-darwin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/homebrew/sbin"
        - "/opt/homebrew/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0/bin"
        - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0@global/bin"
        - "/Users/dheerajmurthy/.rvm/rubies/ruby-3.3.0/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/Users/dheerajmurthy/miniforge3/condabin"
        - "/Users/dheerajmurthy/.nvm/versions/node/v23.9.0/bin"
        - "/Users/dheerajmurthy/.local/bin"
        - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin"
        - "/Users/dheerajmurthy/.pub-cache/bin"
        - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/usr/local/texlive/2024/bin/universal-darwin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/homebrew/sbin"
        - "/opt/homebrew/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pkg/env/active/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/MacGPG2/bin"
        - "/Library/TeX/texbin"
        - "/Applications/Wireshark.app/Contents/MacOS"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/usr/local/go/bin"
        - "/Applications/quarto/bin"
        - "/Users/dheerajmurthy/.cargo/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/Applications/Ghostty.app/Contents/MacOS"
        - "/Users/dheerajmurthy/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/dheerajmurthy/.local/bin"
        - "/opt/homebrew/opt/fzf/bin"
        - "/Users/dheerajmurthy/.rvm/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.4.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/dheerajmurthy/Dev/tooling/flutter/bin/"
      - "/opt/homebrew/opt/postgresql@17/bin/"
      - "/Users/dheerajmurthy/.local/bin/"
      - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin/"
      - "/Users/dheerajmurthy/.pub-cache/bin/"
      - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin/"
      - "/usr/local/texlive/2024/bin/universal-darwin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/homebrew/bin/"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0/bin/"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0@global/bin/"
      - "/Users/dheerajmurthy/.rvm/rubies/ruby-3.3.0/bin/"
      - "/Users/dheerajmurthy/miniforge3/condabin/"
      - "/Users/dheerajmurthy/.nvm/versions/node/v23.9.0/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pkg/env/active/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/MacGPG2/bin/"
      - "/Library/TeX/texbin/"
      - "/Applications/Wireshark.app/Contents/MacOS/"
      - "/usr/local/share/dotnet/"
      - "/Users/dheerajmurthy/.dotnet/tools/"
      - "/usr/local/go/bin/"
      - "/Applications/quarto/bin/"
      - "/Users/dheerajmurthy/.cargo/bin/"
      - "/Applications/Ghostty.app/Contents/MacOS/"
      - "/Users/dheerajmurthy/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/opt/homebrew/opt/fzf/bin/"
      - "/Users/dheerajmurthy/.rvm/bin/"
    searched_directories:
      - "/Users/dheerajmurthy/Dev/tooling/flutter/bin/install_name_tool"
      - "/opt/homebrew/opt/postgresql@17/bin/install_name_tool"
      - "/Users/dheerajmurthy/.local/bin/install_name_tool"
      - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin/install_name_tool"
      - "/Users/dheerajmurthy/.pub-cache/bin/install_name_tool"
      - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin/install_name_tool"
      - "/usr/local/texlive/2024/bin/universal-darwin/install_name_tool"
      - "/opt/homebrew/opt/llvm/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0/bin/install_name_tool"
      - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0@global/bin/install_name_tool"
      - "/Users/dheerajmurthy/.rvm/rubies/ruby-3.3.0/bin/install_name_tool"
      - "/Users/dheerajmurthy/miniforge3/condabin/install_name_tool"
      - "/Users/dheerajmurthy/.nvm/versions/node/v23.9.0/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/Users/dheerajmurthy/.local/bin"
        - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin"
        - "/Users/dheerajmurthy/.pub-cache/bin"
        - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/usr/local/texlive/2024/bin/universal-darwin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/homebrew/sbin"
        - "/opt/homebrew/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0/bin"
        - "/Users/dheerajmurthy/.rvm/gems/ruby-3.3.0@global/bin"
        - "/Users/dheerajmurthy/.rvm/rubies/ruby-3.3.0/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/opt/homebrew/opt/postgresql@17/bin"
        - "/Users/dheerajmurthy/miniforge3/condabin"
        - "/Users/dheerajmurthy/.nvm/versions/node/v23.9.0/bin"
        - "/Users/dheerajmurthy/.local/bin"
        - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin"
        - "/Users/dheerajmurthy/.pub-cache/bin"
        - "/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/usr/local/texlive/2024/bin/universal-darwin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/opt/homebrew/sbin"
        - "/opt/homebrew/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Users/dheerajmurthy/.local/share/solana/install/active_release/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pkg/env/active/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/MacGPG2/bin"
        - "/Library/TeX/texbin"
        - "/Applications/Wireshark.app/Contents/MacOS"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/usr/local/go/bin"
        - "/Applications/quarto/bin"
        - "/Users/dheerajmurthy/.cargo/bin"
        - "/Users/dheerajmurthy/dev/tooling/flutter/bin"
        - "/Applications/Ghostty.app/Contents/MacOS"
        - "/Users/dheerajmurthy/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/dheerajmurthy/.local/bin"
        - "/opt/homebrew/opt/fzf/bin"
        - "/Users/dheerajmurthy/.rvm/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
